# @package _global_


variational: True
latent_dim : 384
kl_weight: 0.23 #if you set decoding to stochastic, make sure to set the training kl_weight correctly. This is the beta value of the Î²-VAE.
tuning_gpus: [0] #gpus used for tuning the kl_weight using the parallel optuna study.
kl_weight_min: 1e-4
kl_weight_max: 1
vae_tuning_freq : 50
n_trials: 5
tuning_fid_feature: 2048
decoding: deterministic


vae_checkpoint_path : /store/CIA/gb511/projects/sbvae/code/experiments/cifar10_vae_tuning/kl_0.23/42/wandb/latest-run/files/vae_checkpoints/epoch=381--val_loss=18.548.ckpt

encoder:
  name: simple_encoder
  base_channel_size: 128
  time_conditional: False
  split_output: True

decoder:
  name: simple_decoder
  base_channel_size: 128

vae_optim:
  lr: 1e-4
  use_scheduler: True
  sch_factor: 0.75
  sch_patience: 100
  sch_min_lr: 1e-6

early_stopping_patience: 300