# @package _global_

defaults:
  - _self_
  # - launcher: slurm_gpu
  - job
  - model: UNET
  - method: dbdsb  #dsb, dbdsb
  - dataset: mnist_transfer
  - vae: simple
  - base_config  # This will override settings from job, model, method, dataset, and vae
  - experiment: cifar10_gaussian_imf  # This will override everything else
  # - override hydra/launcher: submitit_slurm
